application:
version: nautilus
runtime: python27
threadsafe: false
api_version: 1

libraries:
- name: django
  version: latest

handlers:
- url: /static
  static_dir: static

- url: /googlefcab19a6596fa371\.html
  static_files: static/googlefcab19a6596fa371.html
  upload: static/googlefcab19a6596fa371\.html

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /.*
  script: main.py
